---
- name: Configure icam agent
  hosts: all
  vars_files:
    - vars/commonvars.yml
    - vars/icamvars.yml

  tasks:

# ------------- Copy config files ------------------------------------

- import_playbook: filemanager.yml
  vars:
    src_type: "{{config_type}}"
    src_image: "{{config_input_file_src}}"
    untar: no

- name: Configure icam agent
  hosts: all
  vars_files:
    - vars/commonvars.yml
    - vars/icamvars.yml

  tasks:

  - name: Silent config of "{{agent_type}}" agent
    shell: "{{install_dir}}/bin/{{agent_type}}-agent.sh config {{instance}} {{config_input_file_dest}}"
    ignore_errors: true

  - name: Start the "{{agent_type}}" agent
    shell: "{{install_dir}}/bin/{{agent_type}}-agent.sh start {{instance}}"
